### ISSUE TITLE
Where to find nontextured.obj files 

### ISSUE THREAD

**Issue by navjot95** [lianghongzhuo/PointNetGPD#1]
Hi, 

I've downloaded the files from the ycb dataset but seems like they don't come with a nontextured.obj file for each object. Is there a step to generating those? 
For a given object, these are my current files:  kinbody.xml  nontextured.ply  nontextured.stl  textured.dae  textured.mtl  textured.obj  texture_map.png

**Comment by lianghongzhuo** [comment]
Hi, @navjot95 . Thank you  for point this out, I pushed the [code](https://github.com/lianghongzhuo/PointNetGPD/commit/4c6769f938043e8d2a2b44db25a46cba9574a4bc) here.
