### ISSUE TITLE
使用python2还是python3?

### ISSUE THREAD

**Issue by zhangcogito** [lianghongzhuo/PointNetGPD#10]
项目里使用的py2还是py3？
最后使用network需要用ros，只能用py2，所以前面都是用的py2吗？
但是在py2的虚拟环境中无法import meshrender，会报错  
File "~/Desktop/Deep learning grasp detection code/PointGPDCode/venv/local/lib/python2.7/site-packages/pyglet/matrix.py", line 78 
 return matrix @ rmat
                 ^
SyntaxError: invalid syntax
自定义的@运算符在python2是不支持的，似乎这里暗示应该用python3.
所以到底应该用py2呢，还是py3？

**Comment by lianghongzhuo** [comment]
This code was written in python3, but we found that we could not use python3 when we try to run it on ROS. That's why some codes are still in python3, and some are python2, you are well come to write a pull request to convert all code to python2.

**Comment by zhangcogito** [comment]
thanks
