### ISSUE TITLE
Generate dataset problem about python generate-dataset-canny.py [prefix]

### ISSUE THREAD

**Issue by RJ13012416** [lianghongzhuo/PointNetGPD#2]
Hi, Liang. I follow your instructions install the modified meshpy 

https://raw.githubusercontent.com/RJ13012416/GPD/master/2.png?token=AfFDRP5aqVTVH8UG7rImZIvoIZZ9WZHtks5cdgdjwA%3D%3D
https://raw.githubusercontent.com/RJ13012416/GPD/master/3.png?token=AfFDROdZxfYAZe4gLYxV4ZV0-9B3xDTkks5cdgd9wA%3D%3D

While the reselut about generate-dataset-canny.py is 

https://raw.githubusercontent.com/RJ13012416/GPD/master/1.png?token=AfFDRDGuYqPfxxoWq-P0dhST6m1luqqDks5cdgeRwA%3D%3D

And I want to ask how to deal with it ?

**Comment by RJ13012416** [comment]
Hi, Liang.
Some package like matplotlib etc is now support Python3 and I see the code you publish in here is python2 , how do I slove the version conflicts?

**Comment by lianghongzhuo** [comment]
@RJ13012416 
Hi,
1. I can not see the pictures, could you upload again?
2. In the code, only ROS related codes are using python2,  for example [this code](https://github.com/lianghongzhuo/PointNetGPD/blob/master/dex-net/apps/kinect2grasp_python2.py)
For the code to generate dataset and training, it's ok to install the code in python3. And we don't use matplotlib when running ROS codes. 
In short, the rest codes are compatible with both python2 and python3

**Comment by RJ13012416** [comment]
@lianghongzhuo 
Thanks for your reply.

I had running in my computer, while the result of the program is always data about the first model 003_cracker_box 

![default](https://user-images.githubusercontent.com/32588612/53622666-87c0bf00-3c35-11e9-9675-443bde18ee03.png)

![default](https://user-images.githubusercontent.com/32588612/53622718-b9d22100-3c35-11e9-8a1f-ebd38a490440.png)

![default](https://user-images.githubusercontent.com/32588612/53622731-c48cb600-3c35-11e9-9d0c-974276f641ec.png)

Could you help me why this happened ?  and I haven't changed the program .

**Comment by RJ13012416** [comment]
when running the code :

def worker(i, sample_nums, grasp_amount, good_grasp):
    object_name = file_list_all[i][len(home_dir) + 35:]
    print('a worker of task {} start'.format(object_name))


And  the output is :
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start
a worker of task 003_cracker_box start

**Comment by RJ13012416** [comment]
I had slove it, Thx.

**Comment by jeasinema** [comment]
Close due to no potential update.

**Comment by lesleyhaha** [comment]
> when running the code :
> 
> def worker(i, sample_nums, grasp_amount, good_grasp):
> object_name = file_list_all[i][len(home_dir) + 35:]
> print('a worker of task {} start'.format(object_name))
> 
> And the output is :
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start
> a worker of task 003_cracker_box start

How did you solve this problem? I want to know the time you deal with your dataset. Thanks so much!

**Comment by bdenoun** [comment]
@RJ13012416 could you please share how you fixed that? I am also interested. Thank you

**Comment by GeorgeDu** [comment]
> I had slove it, Thx.

I met the same problem, and could you please share how you fixed that? Thanks.

**Comment by GeorgeDu** [comment]
> > I had slove it, Thx.
> 
> I met the same problem, and could you please share how you fixed that? Thanks.

The pool_size could be set according to your machine. If it was set as 1, only one model will be processed.

**Comment by TheJasal** [comment]
@lesleyhaha you should check the output be careful, and I adviced you print the code output setp by step, and then you will find how to mmodified.
Hope that helps!

**Comment by TheJasal** [comment]
@jeasinema @lianghongzhuo _Hi_，I had meet a confused. The topic  **''/table_top"** and **"/table_top_points"** appeared in kinect2grasp_python2.py, I don't konw how they defined.
Would you kind to push the code in this github.
Thanks!
