### ISSUE TITLE
generate grasps too slowly

### ISSUE THREAD

**Issue by yimingli1998** [lianghongzhuo/PointNetGPD#23]
Hi, Liang, 
I tried to generate 7000 grasps for each object but it works too slowly.
Would you mind to share your grasps data(*.pickle  and *.npy file) so that we can use it more convenient?
Thank you very much.

**Comment by lianghongzhuo** [comment]
Sure, I will upload them.

**Comment by lianghongzhuo** [comment]
You can download it here: https://tams.informatik.uni-hamburg.de/research/datasets/PointNetGPD_grasps_dataset.zip

**Comment by yimingli1998** [comment]
> You can download it here: https://tams.informatik.uni-hamburg.de/research/datasets/PointNetGPD_grasps_dataset.zip

Thank you very much!
