### ISSUE TITLE
ICP transform is not correct

### ISSUE THREAD

**Issue by trungpham2606** [lianghongzhuo/PointNetGPD#26]
@lianghongzhuo 
I have tested your provided ICP transfrom (from google pointcloud to depth pointcloud)
For 003_cracker_box, the matching result is like below:
![image](https://user-images.githubusercontent.com/35657426/94386512-1549f500-0172-11eb-97cc-3d912c6d6ad0.png)

**Comment by lianghongzhuo** [comment]
This object is tricky, if you combine multiple point clouds into the scene, you will find that the length of the box in google mesh and rgbd mesh is different. (see the picture blow) So it's hard to say which transform is correct.
![crack_box](https://user-images.githubusercontent.com/16577120/94481128-8ff92b80-01d7-11eb-8dcc-beb080178a2f.png)

**Comment by trungpham2606** [comment]
@lianghongzhuo 
So we should not put it inside the training dataset.
Can you please release the weights again because I had trained the network from scratch but it led me to nothing (the results predicted from pretrained model were not good).
I want to test the potential of the model first before creating new dataset for training.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Some grasp generated is not correct
![image](https://user-images.githubusercontent.com/35657426/94509435-74753b80-023e-11eb-916e-b8b9c60f7595.png)
![image](https://user-images.githubusercontent.com/35657426/94509716-172dba00-023f-11eb-82a6-ae675e8cc33d.png)

**Comment by lianghongzhuo** [comment]
The weight is here:
https://github.com/lianghongzhuo/PointNetGPD/blob/master/data/pointgpd_3class.model

**Comment by trungpham2606** [comment]
@lianghongzhuo 
I know it was there but because you saved the whole model to a pkl file so when you change some file or folders in  the project, other people cant load it by using torch.load(r'....'). that why I was asking you to send the weights file only, not the whole model.

**Comment by lianghongzhuo** [comment]
What's the error msg when you load the model? I have no problem loading this.

**Comment by trungpham2606** [comment]
![image](https://user-images.githubusercontent.com/35657426/94512986-bbb3fa00-0247-11eb-9770-e62696055c5c.png)
here is the error

**Comment by trungpham2606** [comment]
When I opened the .model file, 
![image](https://user-images.githubusercontent.com/35657426/94513026-d6866e80-0247-11eb-9722-22550372ad5a.png)
I can see the change here.
But rename pointGPD to PointNetGPD doesnt fix the error.
Can you reload the model, then save only the weights (torch.save(model.state_dict(),... ) ?

**Comment by lianghongzhuo** [comment]
This looks like a pickle error. See [here](https://github.com/CSAILVision/places365/issues/25#issuecomment-333871990)
Could you try add these codes before loading the model?

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Now the error is 
![image](https://user-images.githubusercontent.com/35657426/94516519-2ff29b80-0250-11eb-88a3-dd3c8b4dfac0.png)

**Comment by trungpham2606** [comment]
I had tested loading the pretrain model in several PC but all of them were not able to load the model.

**Comment by lianghongzhuo** [comment]
Please try on a ubuntu 18.04 computer, Windows is not supported.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
I also tested on Ubuntu 18.04 PC. But still can not load the model successfully.
I believe that you cant load this model in other PC.

**Comment by lianghongzhuo** [comment]
Which code are you testing? I have no problem loading the mode on many computers.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Just simple a test code like this:

import torch
model = torch.load(r''directory to weights')

then the error occurs.

**Comment by lianghongzhuo** [comment]
Just run this [file](https://github.com/lianghongzhuo/PointNetGPD/blob/master/PointNetGPD/main_test.py)
And put the error msg here.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
So strange that when running that main_test.py I dont catch that error.
I realize that the file I had tested is on other folder that outside the PointNetGPD folder. Maybe that is the problem. 
Thank you so much for spending time on my problem.
