### ISSUE TITLE
pretrained results

### ISSUE THREAD

**Issue by trungpham2606** [lianghongzhuo/PointNetGPD#27]
@lianghongzhuo 
I wrote a script based on your kinect2grasp.py to detect grasp poses from point cloud captured from a camera.
The detection part is very good (I generated around 15 grasps for better visualization):
![image](https://user-images.githubusercontent.com/35657426/94636293-e90faf00-02fe-11eb-980e-cfd2f35a92d3.png)

But the classification part is very bad that the model classified all the generated grasps as bad grasps.
![image](https://user-images.githubusercontent.com/35657426/94636410-21af8880-02ff-11eb-9e9d-2ddf447e0059.png)

Do you have any comments about the results I got ?

**Comment by lianghongzhuo** [comment]
Could you share the code and pointcloud you are using? Otherwise, I can't know what's wrong here.

**Comment by trungpham2606** [comment]
can I have your mail ? @lianghongzhuo

**Comment by trungpham2606** [comment]
@lianghongzhuo 
here is the pointcloud and my python code for testing
https://drive.google.com/drive/folders/1JlKvVFy84muuC2AvBBimDjkmID7k7vi3?usp=sharing

**Comment by lianghongzhuo** [comment]
Thank you for the files, I downloaded them. However, I'm busy catching up a deadline, I will check it when I am free.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Thank you. Iam also trying to figure out what is happening when I trained YCB dataset with your pretrained, the loss is quite fluctuating.
I trained 1 object only.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
After making several checks, I think the problem comes from the pretrained model.
I also tested the pretrained model in my data and YCB data as well.
The result for my data is above, and here is for YCB:
![image](https://user-images.githubusercontent.com/35657426/94987309-b7614700-058f-11eb-9d1f-2bbc04e4d762.png)

Then the model also outputs all generated grasp poses are bad grasp.
I also loaded the model and made a training on YCB dataset, the loss is extremely fluctuating.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Can you send me the old weights : pointgpd_chann3_local.model ?

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Can you provide the log file of training session ?

**Comment by lianghongzhuo** [comment]
sorry, I don't save the log file. 
I quick looked commit log, https://github.com/lianghongzhuo/PointNetGPD/commit/e2fce0f5dd4a47dfd979e384e562266014d73e41
Seems I only uploaded one model. There is no "old model"

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Have you checked my scripts that I had sent to you ?

There's error in PointNetGPD/model/dataset.py, in collect_pc function, you missed the line for recalculate the grasp_bottom_center (grasp_bottom_center = -self.ags.gripper.hand_depth * approach + center).

But after changing it and making some inspections, I still cant work with your pretrained model.

**Comment by ACaseOfOrange** [comment]
@trungpham2606 when you run the 3class model, is the 3th element of the output always zero? And the 1st element  of the output always one? The class of the grasp is always 0 or 1 but 2. But some grasps seem to be like good enough.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Had you taken a look at my scripts ?

**Comment by lianghongzhuo** [comment]
Sorry for the delay. I will check it today or tomorrow.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
oh tks ^^
I also changed the pointnet, and retrained the dataset (eliminate the wrong objects), the results are pretty good.
But I think it'll be better if I can use your pretrained weights.
Hope to hear from you soon !

**Comment by lianghongzhuo** [comment]
I checked your code. You have downsampled the input point cloud. But by downsample it . The object point cloud are also down sampled.
The best way is to transform the point cloud into desktop coordinate. Then clip all the point cloud that belong to the table.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Can you test your code on YCB dataset and send me the results ?

**Comment by lianghongzhuo** [comment]
The downsample method is not correct, as the table has a lot of points, downsample all the points together will lose some geometric information. You can first crop the points on the table. By doing that you can keep most geometric information of the object.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
So what happened with the YCB objects ? without any points on table. The results are the same with no good poses ?

**Comment by lianghongzhuo** [comment]
I currently cannot access to the robot in the lab due to the lockdown. When I come back to the office, I can record some point cloud that I use in the experiment. Maybe you can compare the difference. The networks weights work well in my experiment setup.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
I think you dont have to test with robot, just run my script I sent to you and see what's happening. The script I wrote for testing YCB object so that this model must work well on it.

**Comment by lianghongzhuo** [comment]
as I said, the problem in your script is that you downsampling all the point cloud in the ply file. the correct way to do downsampling is to first crop the table points and then downsample the object point cloud only.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Opps the scripts I sent you was not fixed.
Iam gonna send you the script for testing on YCB object.
`import numpy as np
from voxelgrid import VoxelGrid
import pcl
from autolab_core import YamlConfig
from dexnet.grasping import RobotGripper
from dexnet.grasping import GpgGraspSamplerPcl
import os
import glob
import time
import torch
from scipy.stats import mode
import open3d as o3d
# import multiprocessing as mp
# from PointNetGPD.model.pointnet import PointNetCls
from mayavi import mlab
from pyntcloud import PyntCloud
from numba import jit
from model.gpd import *
from main_test import model

# global config:
yaml_config = YamlConfig(r'G:\trung_grasps\PointNetGPD\dex-net\test\config.yaml')
gripper_name = 'robotiq_85'
gripper = RobotGripper.load(gripper_name, r'G:\trung_grasps\PointNetGPD\dex-net\data\grippers')
ags = GpgGraspSamplerPcl(gripper, yaml_config)
value_fc = 0.4  # no use, set a random number
num_grasps = 10
num_workers = 8
max_num_samples = 100

minimal_points_send_to_point_net = 20
marker_life_time = 8

show_bad_grasp = False
save_grasp_related_file = False

show_final_grasp = True
single_obj_testing = False  # if True, it will wait for input before get pointcloud
check_pcd_grasp_points = False



def get_voxel_fun(points_, n):
    get_voxel = VoxelGrid(points_, n_x=n, n_y=n, n_z=n)
    get_voxel.compute()
    points_voxel_ = get_voxel.voxel_centers[get_voxel.voxel_n]
    points_voxel_ = np.unique(points_voxel_, axis=0)
    return points_voxel_


def get_voxel_fun_win(points, n):
    points_ = PyntCloud.from_instance('open3d', points)
    voxel_id = points_.add_structure('voxelgrid', n_x= n, n_y= n, n_z= n)
    get_voxel = points_.structures[voxel_id]
    points_voxel_ = get_voxel.voxel_centers[get_voxel.voxel_n]
    points_voxel_ = np.unique(points_voxel_, axis=0)
    return points_voxel_

def remove_table_points(points_voxel_, vis=True):
    xy_unique = np.unique(points_voxel_[:, 0:2], axis=0)
    new_points_voxel_ = points_voxel_
    pre_del = np.zeros([1])
    for i in range(len(xy_unique)):
        tmp = []
        for j in range(len(points_voxel_)):
            if np.array_equal(points_voxel_[j, 0:2], xy_unique[i]):
                tmp.append(j)
        if len(tmp) < 3:
            tmp = np.array(tmp)
            pre_del = np.hstack([pre_del, tmp])
    if len(pre_del) != 1:
        pre_del = pre_del[1:]
        new_points_voxel_ = np.delete(points_voxel_, pre_del, 0)
    print("Success delete [[ {} ]] points from the table!".format(len(points_voxel_) - len(new_points_voxel_)))

    if vis:
        p = points_voxel_
        mlab.points3d(p[:, 0], p[:, 1], p[:, 2], scale_factor=0.002, color=(1, 0, 0))
        p = new_points_voxel_
        mlab.points3d(p[:, 0], p[:, 1], p[:, 2], scale_factor=0.002, color=(0, 0, 1))
        mlab.points3d(0, 0, 0, scale_factor=0.01, color=(0, 1, 0))  # plot 0 point
        mlab.show()

    return new_points_voxel_


def Resampler(points, k):
    if k <= points.shape[0]:
        rand_idxs = np.random.choice(points.shape[0], k, replace=False)
        return points[rand_idxs, :]
    elif points.shape[0] == k:
        return points
    else:
        rand_idxs = np.concatenate([np.random.choice(points.shape[0], points.shape[0], replace=False),
                                    np.random.choice(points.shape[0], k - points.shape[0], replace=True)])
        return points[rand_idxs, :]

def check_hand_points_fun(real_grasp_):
    ind_points_num = []
    for i in range(len(real_grasp_)):
        grasp_bottom_center = real_grasp_[i][4]
        approach_normal = real_grasp_[i][1]
        binormal = real_grasp_[i][2]
        minor_pc = real_grasp_[i][3]
        local_hand_points = ags.get_hand_points(np.array([0, 0, 0]), np.array([1, 0, 0]), np.array([0, 1, 0]))
        # grasp_bottom_center = -ags.gripper.hand_depth * approach_normal + center_point
        has_points_tmp, ind_points_tmp = ags.check_collision_square(grasp_bottom_center, approach_normal,
                                                                    binormal, minor_pc, points,
                                                                    local_hand_points, "p_open")
        ind_points_num.append(len(ind_points_tmp))

def check_collision_square(grasp_bottom_center, approach_normal, binormal,
                           minor_pc, points_, p, way="p_open"):
    approach_normal = approach_normal.reshape(1, 3)
    approach_normal = approach_normal / np.linalg.norm(approach_normal)
    binormal = binormal.reshape(1, 3)
    binormal = binormal / np.linalg.norm(binormal)
    minor_pc = minor_pc.reshape(1, 3)
    minor_pc = minor_pc / np.linalg.norm(minor_pc)
    matrix_ = np.hstack([approach_normal.T, binormal.T, minor_pc.T])
    grasp_matrix = matrix_.T
    points_copy = points_.copy()
    points_ = points_ - grasp_bottom_center.reshape(1, 3)
    tmp = np.dot(grasp_matrix, points_.T)
    points_g = tmp.T
    use_dataset_py = False

    # p = ags.get_hand_points(grasp_bottom_center, approach_normal, binormal)
    # show_grasp_3d(p)

    if not use_dataset_py:
        if way == "p_open":
            s1, s2, s4, s8 = p[1], p[2], p[4], p[8]
        elif way == "p_left":
            s1, s2, s4, s8 = p[9], p[1], p[10], p[12]
        elif way == "p_right":
            s1, s2, s4, s8 = p[2], p[13], p[3], p[7]
        elif way == "p_bottom":
            s1, s2, s4, s8 = p[11], p[15], p[12], p[20]
        else:
            raise ValueError('No way!')
        a1 = s1[1] < points_g[:, 1]
        a2 = s2[1] > points_g[:, 1]
        a3 = s1[2] > points_g[:, 2]
        a4 = s4[2] < points_g[:, 2]
        a5 = s4[0] > points_g[:, 0]
        a6 = s8[0] < points_g[:, 0]

        a = np.vstack([a1, a2, a3, a4, a5, a6])
        points_in_area = np.where(np.sum(a, axis=0) == len(a))[0]
        if len(points_in_area) == 0:
            has_p = False
        else:
            has_p = True
    # for the way of pointGPD/dataset.py:
    else:
        width = ags.gripper.hand_outer_diameter - 2 * ags.gripper.finger_width
        x_limit = ags.gripper.hand_depth
        z_limit = width / 4
        y_limit = width / 2
        x1 = points_g[:, 0] > -x_limit
        x2 = points_g[:, 0] < 0
        y1 = points_g[:, 1] > -y_limit
        y2 = points_g[:, 1] < y_limit
        z1 = points_g[:, 2] > -z_limit
        z2 = points_g[:, 2] < z_limit
        a = np.vstack([x1, x2, y1, y2, z1, z2])
        points_in_area = np.where(np.sum(a, axis=0) == len(a))[0]
        if len(points_in_area) == 0:
            has_p = False
        else:
            has_p = True

    vis = False

    if vis:
        p = grasp_bottom_center.reshape(1, 3)
        mlab.points3d(p[:, 0], p[:, 1], p[:, 2], scale_factor=0.002, color=(1, 1, 1))
        # mlab.points3d(0, 0, 0, scale_factor=0.002, color=(1, 1, 1))
        p = points_g
        mlab.points3d(p[:, 0], p[:, 1], p[:, 2], scale_factor=0.002, color=(0, 0, 1))
        p = points_g[points_in_area]
        mlab.points3d(p[:, 0], p[:, 1], p[:, 2], scale_factor=0.002, color=(1, 0, 0))
        p = ags.get_hand_points(np.array([0, 0, 0]), np.array([1, 0, 0]), np.array([0, 1, 0]))
        show_grasp_3d(p)
        mlab.show()

    return has_p, points_in_area, points_g

def show_grasp_3d(hand_points, color=(0.003, 0.50196, 0.50196)):
    if color == 'd':
        color = (0.003, 0.50196, 0.50196)
    triangles = [(9, 1, 4), (4, 9, 10), (4, 10, 8), (8, 10, 12), (1, 4, 8), (1, 5, 8),
                 (1, 5, 9), (5, 9, 11), (9, 10, 20), (9, 20, 17), (20, 17, 19), (17, 19, 18),
                 (14, 19, 18), (14, 18, 13), (3, 2, 13), (3, 13, 14), (3, 6, 7), (3, 6, 2),
                 (3, 14, 7), (14, 7, 16), (2, 13, 15), (2, 15, 6), (12, 20, 19), (12, 19, 16),
                 (15, 11, 17), (15, 17, 18), (6, 7, 8), (6, 8, 5)]
    mlab.triangular_mesh(hand_points[:, 0], hand_points[:, 1], hand_points[:, 2],
                         triangles, color=color, opacity=0.5)

def collect_pc(grasp_, pc):
    """
    grasp_bottom_center, normal, major_pc, minor_pc
    """
    grasp_num = len(grasp_)
    grasp_ = np.array(grasp_)
    grasp_ = grasp_.reshape(-1, 5, 3)  # prevent to have grasp that only have number 1
    center_point = grasp_[:, 4]
    approach_normal = grasp_[:, 1]
    binormal = grasp_[:, 2]
    minor_pc = grasp_[:, 3]

    in_ind_ = []
    in_ind_points_ = []

    p = ags.get_hand_points(np.array([0, 0, 0]), np.array([1, 0, 0]), np.array([0, 1, 0]))
    grasp_bottom_center =  center_point #-ags.gripper.hand_depth * approach_normal.reshape(-1, 3) +

    for i_ in range(grasp_num):
        has_p, in_ind_tmp, points_g = check_collision_square(grasp_bottom_center[i_], approach_normal[i_],
                                                             binormal[i_], minor_pc[i_], pc, p)
        in_ind_.append(in_ind_tmp)
        in_ind_points_.append(points_g[in_ind_[i_]])
    return in_ind_, in_ind_points_

def normalize(point_cloud):
    point_cloud = point_cloud.T
    norm_pcl = point_cloud - np.mean(point_cloud, axis= 0)
    norm_pcl /= np.max(np.linalg.norm(norm_pcl, axis= 1))
    norm_pcl = norm_pcl.T
    return norm_pcl

def cal_grasp(points_):
    start = time.time()
    n = 150 # n_voxel  # parameter related to voxel method
    points_voxel_ = get_voxel_fun(points_, n)
    print('time for getting voxel ', str(time.time() - start))

    if len(points_) < 2000:  # should be a parameter
        while len(points_voxel_) < len(points_) - 15:
            points_voxel_ = get_voxel_fun_win(points_, n)
            n = n + 100

    points_ = points_voxel_

    remove_points = False

    if remove_points:
        points_ = remove_table_points(points_, vis=True)

    point_cloud = pcl.PointCloud(points_)
    norm = point_cloud.make_NormalEstimation()
    norm.set_KSearch(30)  # critical parameter when calculating the norms
    normals = norm.compute()
    surface_normal = normals.to_array()
    surface_normal = surface_normal[:, 0:3]

    # FIXED: cam_pos_
    cam_pos_ = [0, 0, m]

    vector_p2cam = cam_pos_ - points_
    vector_p2cam = vector_p2cam / np.linalg.norm(vector_p2cam, axis=1).reshape(-1, 1)
    tmp = np.dot(vector_p2cam, surface_normal.T).diagonal()
    angel = np.arccos(np.clip(tmp, -1.0, 1.0))
    wrong_dir_norm = np.where(angel > np.pi * 0.5)[0]
    tmp = np.ones([len(angel), 3])
    tmp[wrong_dir_norm, :] = -1
    surface_normal = surface_normal * tmp
    select_point_above_table = 0.01
    # #  modify of gpg: make it as a parameter. avoid select points near the table.
    points_for_sample = points_[points_[:, 2] > select_point_above_table]

    if len(points_for_sample) == 0:
        return [], points_, surface_normal

    yaml_config['metrics']['robust_ferrari_canny']['friction_coef'] = value_fc

    start1 = time.time()
    if True:
        grasps_together_ = ags.sample_grasps(point_cloud, points_for_sample, surface_normal, num_grasps,
                                             max_num_samples=max_num_samples, show_final_grasp=show_final_grasp)


    print('time for generating grasp poses ', str(time.time() - start1))

    # check_grasp_points_num = True  # evaluate the number of points in a grasp
    # check_hand_points_fun(grasps_together_) if check_grasp_points_num else 0

    _, in_ind_points = collect_pc(grasps_together_, points_)

    # for p in in_ind_points:
    #     print('number of points in grasp', len(p))

    score = []  # should be 0 or 1
    score_value = []  # should be float [0, 1]
    ind_good_grasp = []
    ind_bad_grasp = []
    repeat = 1
    real_good_grasp = []
    real_bad_grasp = []
    real_score_value = []

    for ii in range(len(in_ind_points)):
        if in_ind_points[ii].shape[0] < minimal_points_send_to_point_net:
            score.append(0)
            score_value.append(0.0)
            if show_bad_grasp:
                ind_bad_grasp.append(ii)
        else:
            predict = []
            grasp_score = []
            for _ in range(repeat):
                if len(in_ind_points[ii]) >= input_points_num:
                    points_modify = in_ind_points[ii][np.random.choice(len(in_ind_points[ii]),
                                                                       input_points_num, replace=False)]
                else:
                    points_modify = in_ind_points[ii][np.random.choice(len(in_ind_points[ii]),
                                                                       input_points_num, replace=True)]

                if_good_grasp, grasp_score_tmp = detect_network(model.eval(), points_modify)
                predict.append(if_good_grasp.item())
                grasp_score.append(grasp_score_tmp)

            predict_vote = mode(predict)[0][0]  # most occuring in a list

            grasp_score = np.array(grasp_score)
            which_one_is_best = 2

            score_vote = np.mean(grasp_score[np.where(predict == predict_vote)][:, 0, which_one_is_best])
            score.append(predict_vote)
            score_value.append(score_vote)


            if score[ii] == which_one_is_best:
                ind_good_grasp.append(ii)
            else:
                ind_bad_grasp.append(ii)

    print('score_value', score_value)
    print("Got {} good grasps, and {} bad grasps".format(len(ind_good_grasp),
                                                         len(in_ind_points) - len(ind_good_grasp)))

    if len(ind_good_grasp) != 0:
        real_good_grasp = [grasps_together_[i] for i in ind_good_grasp]
        real_score_value = [score_value[i] for i in ind_good_grasp]

    # if len(ind_bad_grasp) != 0:
    #     real_bad_grasp = [grasps_together_[i] for i in ind_bad_grasp]
    #     real_score_value = [score_value[i] for i in ind_bad_grasp]

    sorted_value_ind = list(index for index, item in sorted(enumerate(real_score_value),
                                                            key=lambda item: item[1],
                                                            reverse=True))

    sorted_real_good_grasp = [real_good_grasp[i] for i in sorted_value_ind]
    real_good_grasp = sorted_real_good_grasp
    real_score_value = sorted(real_score_value, reverse=True)

    if len(real_good_grasp) != 0:
        ags.show_detected_grasp(point_cloud, real_good_grasp, show_final_grasp= True)

    print('*' * 80)
    return grasps_together_, points_, surface_normal


def detect_network(model_, local_pc):
    local_pc = local_pc.T
    local_pc = local_pc[np.newaxis, ...]
    local_pc = torch.FloatTensor(local_pc)
    local_pc = local_pc.cuda()

    output, _ = model_(local_pc)  # N*C
    output = output.softmax(1)
    pred = output.data.max(1, keepdim=True)[1]
    output = output.cpu()
    return pred[0], output.data.numpy()


if __name__ == '__main__':
    input_points_num = 500

    obj_path = r'G:\grasp_dataset\ycb_mesh\004_sugar_box\google_16k\nontextured.ply'
    slm = o3d.io.read_point_cloud(obj_path)
    points = np.array(slm.points)

    m = np.max(points[:, 2]) + 1
    # points[:, 2] = 0.1 + points[:, 2]
    points_reduce = points if len(points) < 50000 else Resampler(points, 30000)

    real_grasp, points, normals_cal = cal_grasp(points_reduce)
`

**Comment by trungpham2606** [comment]
@lianghongzhuo 
The result is as below 
![image](https://user-images.githubusercontent.com/35657426/103754621-2c389700-503f-11eb-9cfb-d8456b2d2e93.png)
![image](https://user-images.githubusercontent.com/35657426/103754651-365a9580-503f-11eb-8e09-70795b9f17b8.png)

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Excuse me but have you tested my script. Iam looking forward to your help.

**Comment by trungpham2606** [comment]
@lianghongzhuo

**Comment by lianghongzhuo** [comment]
Sorry for the late reply. 
This model is not trained on the ycb google point cloud. The model is trained on the Raw RGBD data.
For example this  [LINK](http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/data/berkeley/003_cracker_box/003_cracker_box_berkeley_rgbd.tgz).
If you test on the ycb google point cloud (the laser scan) data, it might fail.
If you have a depth camera (kinect or realsense for example) you can try our model again to see the difference. I will also upload some example point cloud in the future.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Sorry but what is the LINK that you had provided ? When I clicked on it, nothing happened.
Can you double check the LINK ?

**Comment by trungpham2606** [comment]
@lianghongzhuo 
We still have to convert the RGBdepth image (captured from the camera) to point cloud, so what is the difference here ? 
Can you make it clear for me ?

**Comment by lianghongzhuo** [comment]
http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/data/berkeley/003_cracker_box/003_cracker_box_berkeley_rgbd.tgz
the link is the download link for ycb rgbd data

**Comment by trungpham2606** [comment]
@lianghongzhuo 
Thank you for the link.
1 more problem is that with boxes, I always meet this failure:
![image](https://user-images.githubusercontent.com/35657426/105329285-8f135c00-5c03-11eb-975f-b7608859cb6d.png)
it should be bad pose instead of good pose.

**Comment by trungpham2606** [comment]
@lianghongzhuo 
If I want to use different gripper, do I have to re-create the dataset according to my gripper's config ?

**Comment by trungpham2606** [comment]
@lianghongzhuo

**Comment by Twilight89** [comment]
@trungpham2606 Hi~ I want to ask that in the kinect2grasp.py, 
        kinect_data = rospy.wait_for_message("table_top_points", PointCloud2)
the kinect_data is based on kinect coordinate, right? So I can directly use /kinect_V2/depth/points topic published by kinect? 
And in
        real_grasp, points, normals_cal = cal_grasp(kinect_data, cam_pos)
the points here is also based on kinect coordinate(I checked the data and in my production, it's based on kinect coordinate)? I am confused because I send cam_pos in, hope to get points based on table_top coordinate.
I don't know why, leading to my result like follow:(I use rviz, failing to import mayavi )
Hope for you reply, thanks a lot!
![grasp_view1](https://user-images.githubusercontent.com/60816348/110406272-e8085800-80bc-11eb-9736-810bcc5d8072.png)

**Comment by trungpham2606** [comment]
@Twilight89 
According to author's code, the objects point cloud are on world coordinate. I didnt use ROS for visualizing but using real camera instead.

**Comment by Twilight89** [comment]
@trungpham2606 Thanks a lot for your reply. So points in 
real_grasp, points, normals_cal = cal_grasp(kinect_data, cam_pos)
are on world coordinate? But kinect_data is on camera coordinate, do I need to tranform kinect_data(camera_frame) to points(world_frame). 
I used to think points are on world coordinate, but I checked the data in my repo, they are on camera coordinate. I thought I have sent cam_pos in so the tranformation was done.
Briefly, now I should get points in world frame(now they are camera frame), is that your meaning?
Hope for reply~

**Comment by trungpham2606** [comment]
@Twilight89 
Yes, you should get points in world frame.

**Comment by Twilight89** [comment]
@trungpham2606 thanks again~
I want to know in your repo, is kinect_data in camera frame? because in this line
   cam_pos, _ = listener.lookupTransform('/table_top', '/kinect2_ir_optical_frame', rospy.Time(0)) 
we can get cam_pos, and send in 
   real_grasp, points, normals_cal = cal_grasp(kinect_data, cam_pos)
I used to think the tranformation was done due to I sent in cam_pos. If not, why we should get cam_pos?
Hoping for reply

**Comment by trungpham2606** [comment]
@Twilight89 
Sorry but we didnt run on ROS, we test on real camera(realsense) and robot(UR5) directly. In our experiment, the pointcloud and cam_pos are both on world coordinates.

**Comment by Twilight89** [comment]
@trungpham2606 
Sorry I am a little confused. Did you change something about 'data transform' after git this code. I think there is no difference between simulation and reality. 
In my simulation repo, the cam_pos is on world coordinate, too. And I think in real camera, the directly data it got is on camera coordinate, too.
If this, I just found my points are on carema coordinate, which is unnormal, so did you do any transformation to change points to world frame?

**Comment by Twilight89** [comment]
@trungpham2606 
Thanks a lot for your patience, I'll try it later. Hope your problem can be solved soon.

**Comment by trungpham2606** [comment]
@Twilight89 
Thank you, my problem has been solved. Iam gonna close this issue right now !
