### ISSUE TITLE
How much time to generate dataset?

### ISSUE THREAD

**Issue by iory** [lianghongzhuo/PointNetGPD#3]
Thanks for your great works!

I would like to train PointNetGPD.
And data generation took much time and it is not finished yet.
I want you to tell me that how much time to generate a dataset  for reference.

**Comment by lianghongzhuo** [comment]
Estimated running time at our Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz dual CPU with 56 Threads is 36 hours. Please also remove objects beyond the capacity of the gripper.

**Comment by iory** [comment]
Thank you!

>  Please also remove objects beyond the capacity of the gripper.

OK. I will retry data generation.

**Comment by lesleyhaha** [comment]
> Estimated running time at our Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz dual CPU with 56 Threads is 36 hours. Please also remove objects beyond the capacity of the gripper.

Thanks! I also has a question that  how much time to generate a object in the dataset, like 002_master_chef_can.

**Comment by zhangcogito** [comment]
> > Estimated running time at our Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz dual CPU with 56 Threads is 36 hours. Please also remove objects beyond the capacity of the gripper.
> 
> Thanks! I also has a question that how much time to generate a object in the dataset, like 002_master_chef_can.

Have you resolved it? I run "python generate-dataset-canny.py [prefix]". It start generating the grasp of 002_master_chef_can. It has run for several hours and still not stops. Why it costs so much time to generate grasps for only 1 object?

**Comment by v-wewei** [comment]
@zhangcogito hi，did you solve the problem for the time consuming about generating grasp for objects?

**Comment by toannguyen1904** [comment]
hello, any updates on the generation time?
