### ISSUE TITLE
Computing grasp score is different from written in the paper?

### ISSUE THREAD

**Issue by Guptajakala** [lianghongzhuo/PointNetGPD#39]
Hi, thanks for the great repo!
In your paper, if the friction coeff is `miu`, then the score should be `1/miu`. But in your implementation, I found you are directly adding `miu` as part of the score.
https://github.com/lianghongzhuo/PointNetGPD/blob/5d3453df192866968d03569eb4da66b0fba8bfd6/PointNetGPD/model/dataset.py#L265
The level_score is basically the friction coeff `miu` when you are saving the grasp training data according to the code. Is my understanding right?

**Comment by lianghongzhuo** [comment]
The `level_score = 1/miu`, so the lower the friction coeff, the higher the score

**Comment by Guptajakala** [comment]
During grasp training data generation, I saw here the second term of a grasp is value_fc, is it the `miu`?
https://github.com/lianghongzhuo/PointNetGPD/blob/5d3453df192866968d03569eb4da66b0fba8bfd6/dex-net/apps/generate-dataset-canny.py#L133

Then in the data loader, the grasp data is read and the second term is `level_score`, which should be the `miu` during generation. 
https://github.com/lianghongzhuo/PointNetGPD/blob/5d3453df192866968d03569eb4da66b0fba8bfd6/PointNetGPD/model/dataset.py#L799
Could you explain where did you change the it to `1/miu`?

**Comment by lianghongzhuo** [comment]
Sorry I forget the detail of the implementation. In the implementation, the lower the value the better the quality.
see the code:
https://github.com/lianghongzhuo/PointNetGPD/blob/master/PointNetGPD/model/dataset.py#L537-L543
We did not use 1/miu in the labeling process.

**Comment by Guptajakala** [comment]
I see, thanks for the clarification!
