### ISSUE TITLE
error:Install python pcl library python-pcl

### ISSUE THREAD

**Issue by quyouyuan** [lianghongzhuo/PointNetGPD#45]
Hello!liang! When I use your 'Python PCL' library to install, I report an error! Can you tell me how to solve it? The error is as follows:
setup.py: error: cannot find PCL, tried
    pkg-config pcl_common-1.9
    pkg-config pcl_common-1.8
    pkg-config pcl_common-1.7
    pkg-config pcl_common-1.6
    pkg-config pcl_common

**Comment by aniketghodake10** [comment]
> Hello!liang! When I use your 'Python PCL' library to install, I report an error! Can you tell me how to solve it? The error is as follows: setup.py: error: cannot find PCL, tried pkg-config pcl_common-1.9 pkg-config pcl_common-1.8 pkg-config pcl_common-1.7 pkg-config pcl_common-1.6 pkg-config pcl_common

#47

**Comment by lianghongzhuo** [comment]
I have switched the code to open3d
