### ISSUE TITLE
Question about the autolab_core

### ISSUE THREAD

**Issue by PPatrickGU** [lianghongzhuo/PointNetGPD#46]
Hello,

I've met a problem when I try to run your code of _generate-daset-canny.py_:

`WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable`

Have you ever met this kind of problem? I'm sure having followed the same steps as written in your README.

Thx a lot.

**Comment by lianghongzhuo** [comment]
This can be ignored. This warning is only because we did not install autolab_core as ROS package.
