### ISSUE TITLE
read_grasps_from_file.py mayavi qt4 error

### ISSUE THREAD

**Issue by aniketghodake10** [lianghongzhuo/PointNetGPD#48]
Ubuntu 20.04 python 3.6 conda environment

Same issue like this https://askpythonquestions.com/2022/02/06/python-loading-mayavi-mlab-throws-attribute-error-probably-from-qt-loading-mayavi-works-fine/

Any solution ??

**Comment by penghongguang** [comment]
Have you solved it？I  meet the same problem.

**Comment by penghongguang** [comment]
> Ubuntu 20.04 python 3.6 conda environment
> 
> Same issue like this https://askpythonquestions.com/2022/02/06/python-loading-mayavi-mlab-throws-attribute-error-probably-from-qt-loading-mayavi-works-fine/
> 
> Any solution ??

Have you solved it？I meet the same problem.

**Comment by aniketghodake10** [comment]
> > Ubuntu 20.04 python 3.6 conda environment
> > Same issue like this https://askpythonquestions.com/2022/02/06/python-loading-mayavi-mlab-throws-attribute-error-probably-from-qt-loading-mayavi-works-fine/
> > Any solution ??
> 
> Have you solved it？I meet the same problem.

not yet

**Comment by xiaofeiso** [comment]
you can see this:https://github.com/wkentaro/labelme/issues/842,but i have another problems.

**Comment by lianghongzhuo** [comment]
if you use conda, you can try `conda install mayavi -c conda-forge`
my system is python3.10, and there is no problem
