### ISSUE TITLE
error：python main_1v.py --epoch 200 --mode train --batch-size 64 

### ISSUE THREAD

**Issue by xmkkkkkk** [lianghongzhuo/PointNetGPD#57]
Hello Mr. Liang, I re-downloaded your PointNetGPD, but when I run 'python main_1v.py --epoch 200 --mode train --batch-size  64’, there is such an error.I don't launch a tensorboard for monitoring, I don't know if this is the reason. And I changed ‘--batch-size’ but still the same error. Here is my dataset path and the error. Thanks!
![2023-05-31 14-10-39 的屏幕截图](https://github.com/lianghongzhuo/PointNetGPD/assets/118176999/0ff66922-1e1b-4196-8efe-8f47e960ee33)
![2023-05-31 14-06-52 的屏幕截图](https://github.com/lianghongzhuo/PointNetGPD/assets/118176999/aa0c6060-1bf2-4153-8f74-5c432b20e051)

**Comment by xmkkkkkk** [comment]
The python3.10 I used at first also had this error.Then I installed a lower version of pytorch with pyhton3.7 env and this error is also.

**Comment by lianghongzhuo** [comment]
I am writing patches to fix this, the dataset path has changed. Please put your ycb object dataset (rgbd and google 512k) at `$PointNetGPD_FOLDER//data/ycb-tools/models/ycb`

**Comment by lianghongzhuo** [comment]
this issuse is solved by https://github.com/lianghongzhuo/PointNetGPD/commit/3b53a495b8f730543f273504df4e5d27c3699572

**Comment by xmkkkkkk** [comment]
Dear,Mr. Liang, Thank you for your answer, but now there is a new problem. I want to know at which step the file it said was generated. I really don’t have this file.
![64e28226b9ca1328ec2364b181ea124](https://github.com/lianghongzhuo/PointNetGPD/assets/118176999/1c021a14-d9fa-4c74-bffb-417f7dea35c6)

**Comment by lianghongzhuo** [comment]
Hi, this is because of the missing model folder, see 336eb9e9cbb534dea36b3e92e0d1b7adef13d7f3 for the up to date code
