### ISSUE TITLE
python-pcl require python >=3.5

### ISSUE THREAD

**Issue by zhangcogito** [lianghongzhuo/PointNetGPD#9]
Because it need the ros and python2, I tried to install python-pcl in python2. But I get the error: RuntimeError: Python version >= 3.5 required. How can I install python-pcl in python2? In the python-pcl https://github.com/strawlab/python-pcl repositor, it say "This release has been tested on Linux Ubuntu 18.04 with Python 2.7.6, 3.5.x".

**Comment by zhangcogito** [comment]
I have resolved it. The reason is that my numpy is 1.13. But python-pcl need numpy>=1.6.1,!=1.6.2. After I update my numpy to 1.6.1, it works.

**Comment by lianghongzhuo** [comment]
Good to know that.
By the way, you can also use conda environment to install python-pcl.
